//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebServiceDB.ServiceSimpleReservations {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSimpleReservations.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento allReservationsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/allReservations", ReplyAction="*")]
        HotelWebServiceDB.ServiceSimpleReservations.allReservationsResponse allReservations(HotelWebServiceDB.ServiceSimpleReservations.allReservationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/allReservations", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceSimpleReservations.allReservationsResponse> allReservationsAsync(HotelWebServiceDB.ServiceSimpleReservations.allReservationsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento simplesReservationsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/simplesReservations", ReplyAction="*")]
        HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsResponse simplesReservations(HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/simplesReservations", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsResponse> simplesReservationsAsync(HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class allReservationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="allReservations", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceSimpleReservations.allReservationsRequestBody Body;
        
        public allReservationsRequest() {
        }
        
        public allReservationsRequest(HotelWebServiceDB.ServiceSimpleReservations.allReservationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class allReservationsRequestBody {
        
        public allReservationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class allReservationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="allReservationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceSimpleReservations.allReservationsResponseBody Body;
        
        public allReservationsResponse() {
        }
        
        public allReservationsResponse(HotelWebServiceDB.ServiceSimpleReservations.allReservationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class allReservationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string allReservationsResult;
        
        public allReservationsResponseBody() {
        }
        
        public allReservationsResponseBody(string allReservationsResult) {
            this.allReservationsResult = allReservationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class simplesReservationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="simplesReservations", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsRequestBody Body;
        
        public simplesReservationsRequest() {
        }
        
        public simplesReservationsRequest(HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class simplesReservationsRequestBody {
        
        public simplesReservationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class simplesReservationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="simplesReservationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsResponseBody Body;
        
        public simplesReservationsResponse() {
        }
        
        public simplesReservationsResponse(HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class simplesReservationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string simplesReservationsResult;
        
        public simplesReservationsResponseBody() {
        }
        
        public simplesReservationsResponseBody(string simplesReservationsResult) {
            this.simplesReservationsResult = simplesReservationsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : HotelWebServiceDB.ServiceSimpleReservations.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<HotelWebServiceDB.ServiceSimpleReservations.WebService1Soap>, HotelWebServiceDB.ServiceSimpleReservations.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelWebServiceDB.ServiceSimpleReservations.allReservationsResponse HotelWebServiceDB.ServiceSimpleReservations.WebService1Soap.allReservations(HotelWebServiceDB.ServiceSimpleReservations.allReservationsRequest request) {
            return base.Channel.allReservations(request);
        }
        
        public string allReservations() {
            HotelWebServiceDB.ServiceSimpleReservations.allReservationsRequest inValue = new HotelWebServiceDB.ServiceSimpleReservations.allReservationsRequest();
            inValue.Body = new HotelWebServiceDB.ServiceSimpleReservations.allReservationsRequestBody();
            HotelWebServiceDB.ServiceSimpleReservations.allReservationsResponse retVal = ((HotelWebServiceDB.ServiceSimpleReservations.WebService1Soap)(this)).allReservations(inValue);
            return retVal.Body.allReservationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceSimpleReservations.allReservationsResponse> HotelWebServiceDB.ServiceSimpleReservations.WebService1Soap.allReservationsAsync(HotelWebServiceDB.ServiceSimpleReservations.allReservationsRequest request) {
            return base.Channel.allReservationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelWebServiceDB.ServiceSimpleReservations.allReservationsResponse> allReservationsAsync() {
            HotelWebServiceDB.ServiceSimpleReservations.allReservationsRequest inValue = new HotelWebServiceDB.ServiceSimpleReservations.allReservationsRequest();
            inValue.Body = new HotelWebServiceDB.ServiceSimpleReservations.allReservationsRequestBody();
            return ((HotelWebServiceDB.ServiceSimpleReservations.WebService1Soap)(this)).allReservationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsResponse HotelWebServiceDB.ServiceSimpleReservations.WebService1Soap.simplesReservations(HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsRequest request) {
            return base.Channel.simplesReservations(request);
        }
        
        public string simplesReservations() {
            HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsRequest inValue = new HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsRequest();
            inValue.Body = new HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsRequestBody();
            HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsResponse retVal = ((HotelWebServiceDB.ServiceSimpleReservations.WebService1Soap)(this)).simplesReservations(inValue);
            return retVal.Body.simplesReservationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsResponse> HotelWebServiceDB.ServiceSimpleReservations.WebService1Soap.simplesReservationsAsync(HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsRequest request) {
            return base.Channel.simplesReservationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsResponse> simplesReservationsAsync() {
            HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsRequest inValue = new HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsRequest();
            inValue.Body = new HotelWebServiceDB.ServiceSimpleReservations.simplesReservationsRequestBody();
            return ((HotelWebServiceDB.ServiceSimpleReservations.WebService1Soap)(this)).simplesReservationsAsync(inValue);
        }
    }
}
