//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebServiceDB.ServiceCiReservas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCiReservas.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento allReservationsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/allReservations", ReplyAction="*")]
        HotelWebServiceDB.ServiceCiReservas.allReservationsResponse allReservations(HotelWebServiceDB.ServiceCiReservas.allReservationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/allReservations", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceCiReservas.allReservationsResponse> allReservationsAsync(HotelWebServiceDB.ServiceCiReservas.allReservationsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento simplesReservationsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/simplesReservations", ReplyAction="*")]
        HotelWebServiceDB.ServiceCiReservas.simplesReservationsResponse simplesReservations(HotelWebServiceDB.ServiceCiReservas.simplesReservationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/simplesReservations", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceCiReservas.simplesReservationsResponse> simplesReservationsAsync(HotelWebServiceDB.ServiceCiReservas.simplesReservationsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento todayReservationsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/todayReservations", ReplyAction="*")]
        HotelWebServiceDB.ServiceCiReservas.todayReservationsResponse todayReservations(HotelWebServiceDB.ServiceCiReservas.todayReservationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/todayReservations", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceCiReservas.todayReservationsResponse> todayReservationsAsync(HotelWebServiceDB.ServiceCiReservas.todayReservationsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reservasPorCI", ReplyAction="*")]
        HotelWebServiceDB.ServiceCiReservas.reservasPorCIResponse reservasPorCI(HotelWebServiceDB.ServiceCiReservas.reservasPorCIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reservasPorCI", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceCiReservas.reservasPorCIResponse> reservasPorCIAsync(HotelWebServiceDB.ServiceCiReservas.reservasPorCIRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class allReservationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="allReservations", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceCiReservas.allReservationsRequestBody Body;
        
        public allReservationsRequest() {
        }
        
        public allReservationsRequest(HotelWebServiceDB.ServiceCiReservas.allReservationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class allReservationsRequestBody {
        
        public allReservationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class allReservationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="allReservationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceCiReservas.allReservationsResponseBody Body;
        
        public allReservationsResponse() {
        }
        
        public allReservationsResponse(HotelWebServiceDB.ServiceCiReservas.allReservationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class allReservationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string allReservationsResult;
        
        public allReservationsResponseBody() {
        }
        
        public allReservationsResponseBody(string allReservationsResult) {
            this.allReservationsResult = allReservationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class simplesReservationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="simplesReservations", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceCiReservas.simplesReservationsRequestBody Body;
        
        public simplesReservationsRequest() {
        }
        
        public simplesReservationsRequest(HotelWebServiceDB.ServiceCiReservas.simplesReservationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class simplesReservationsRequestBody {
        
        public simplesReservationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class simplesReservationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="simplesReservationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceCiReservas.simplesReservationsResponseBody Body;
        
        public simplesReservationsResponse() {
        }
        
        public simplesReservationsResponse(HotelWebServiceDB.ServiceCiReservas.simplesReservationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class simplesReservationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string simplesReservationsResult;
        
        public simplesReservationsResponseBody() {
        }
        
        public simplesReservationsResponseBody(string simplesReservationsResult) {
            this.simplesReservationsResult = simplesReservationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class todayReservationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="todayReservations", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceCiReservas.todayReservationsRequestBody Body;
        
        public todayReservationsRequest() {
        }
        
        public todayReservationsRequest(HotelWebServiceDB.ServiceCiReservas.todayReservationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class todayReservationsRequestBody {
        
        public todayReservationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class todayReservationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="todayReservationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceCiReservas.todayReservationsResponseBody Body;
        
        public todayReservationsResponse() {
        }
        
        public todayReservationsResponse(HotelWebServiceDB.ServiceCiReservas.todayReservationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class todayReservationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string todayReservationsResult;
        
        public todayReservationsResponseBody() {
        }
        
        public todayReservationsResponseBody(string todayReservationsResult) {
            this.todayReservationsResult = todayReservationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reservasPorCIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reservasPorCI", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceCiReservas.reservasPorCIRequestBody Body;
        
        public reservasPorCIRequest() {
        }
        
        public reservasPorCIRequest(HotelWebServiceDB.ServiceCiReservas.reservasPorCIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class reservasPorCIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public reservasPorCIRequestBody() {
        }
        
        public reservasPorCIRequestBody(string ci) {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reservasPorCIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reservasPorCIResponse", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceCiReservas.reservasPorCIResponseBody Body;
        
        public reservasPorCIResponse() {
        }
        
        public reservasPorCIResponse(HotelWebServiceDB.ServiceCiReservas.reservasPorCIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class reservasPorCIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reservasPorCIResult;
        
        public reservasPorCIResponseBody() {
        }
        
        public reservasPorCIResponseBody(string reservasPorCIResult) {
            this.reservasPorCIResult = reservasPorCIResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : HotelWebServiceDB.ServiceCiReservas.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<HotelWebServiceDB.ServiceCiReservas.WebService1Soap>, HotelWebServiceDB.ServiceCiReservas.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelWebServiceDB.ServiceCiReservas.allReservationsResponse HotelWebServiceDB.ServiceCiReservas.WebService1Soap.allReservations(HotelWebServiceDB.ServiceCiReservas.allReservationsRequest request) {
            return base.Channel.allReservations(request);
        }
        
        public string allReservations() {
            HotelWebServiceDB.ServiceCiReservas.allReservationsRequest inValue = new HotelWebServiceDB.ServiceCiReservas.allReservationsRequest();
            inValue.Body = new HotelWebServiceDB.ServiceCiReservas.allReservationsRequestBody();
            HotelWebServiceDB.ServiceCiReservas.allReservationsResponse retVal = ((HotelWebServiceDB.ServiceCiReservas.WebService1Soap)(this)).allReservations(inValue);
            return retVal.Body.allReservationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceCiReservas.allReservationsResponse> HotelWebServiceDB.ServiceCiReservas.WebService1Soap.allReservationsAsync(HotelWebServiceDB.ServiceCiReservas.allReservationsRequest request) {
            return base.Channel.allReservationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelWebServiceDB.ServiceCiReservas.allReservationsResponse> allReservationsAsync() {
            HotelWebServiceDB.ServiceCiReservas.allReservationsRequest inValue = new HotelWebServiceDB.ServiceCiReservas.allReservationsRequest();
            inValue.Body = new HotelWebServiceDB.ServiceCiReservas.allReservationsRequestBody();
            return ((HotelWebServiceDB.ServiceCiReservas.WebService1Soap)(this)).allReservationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelWebServiceDB.ServiceCiReservas.simplesReservationsResponse HotelWebServiceDB.ServiceCiReservas.WebService1Soap.simplesReservations(HotelWebServiceDB.ServiceCiReservas.simplesReservationsRequest request) {
            return base.Channel.simplesReservations(request);
        }
        
        public string simplesReservations() {
            HotelWebServiceDB.ServiceCiReservas.simplesReservationsRequest inValue = new HotelWebServiceDB.ServiceCiReservas.simplesReservationsRequest();
            inValue.Body = new HotelWebServiceDB.ServiceCiReservas.simplesReservationsRequestBody();
            HotelWebServiceDB.ServiceCiReservas.simplesReservationsResponse retVal = ((HotelWebServiceDB.ServiceCiReservas.WebService1Soap)(this)).simplesReservations(inValue);
            return retVal.Body.simplesReservationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceCiReservas.simplesReservationsResponse> HotelWebServiceDB.ServiceCiReservas.WebService1Soap.simplesReservationsAsync(HotelWebServiceDB.ServiceCiReservas.simplesReservationsRequest request) {
            return base.Channel.simplesReservationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelWebServiceDB.ServiceCiReservas.simplesReservationsResponse> simplesReservationsAsync() {
            HotelWebServiceDB.ServiceCiReservas.simplesReservationsRequest inValue = new HotelWebServiceDB.ServiceCiReservas.simplesReservationsRequest();
            inValue.Body = new HotelWebServiceDB.ServiceCiReservas.simplesReservationsRequestBody();
            return ((HotelWebServiceDB.ServiceCiReservas.WebService1Soap)(this)).simplesReservationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelWebServiceDB.ServiceCiReservas.todayReservationsResponse HotelWebServiceDB.ServiceCiReservas.WebService1Soap.todayReservations(HotelWebServiceDB.ServiceCiReservas.todayReservationsRequest request) {
            return base.Channel.todayReservations(request);
        }
        
        public string todayReservations() {
            HotelWebServiceDB.ServiceCiReservas.todayReservationsRequest inValue = new HotelWebServiceDB.ServiceCiReservas.todayReservationsRequest();
            inValue.Body = new HotelWebServiceDB.ServiceCiReservas.todayReservationsRequestBody();
            HotelWebServiceDB.ServiceCiReservas.todayReservationsResponse retVal = ((HotelWebServiceDB.ServiceCiReservas.WebService1Soap)(this)).todayReservations(inValue);
            return retVal.Body.todayReservationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceCiReservas.todayReservationsResponse> HotelWebServiceDB.ServiceCiReservas.WebService1Soap.todayReservationsAsync(HotelWebServiceDB.ServiceCiReservas.todayReservationsRequest request) {
            return base.Channel.todayReservationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelWebServiceDB.ServiceCiReservas.todayReservationsResponse> todayReservationsAsync() {
            HotelWebServiceDB.ServiceCiReservas.todayReservationsRequest inValue = new HotelWebServiceDB.ServiceCiReservas.todayReservationsRequest();
            inValue.Body = new HotelWebServiceDB.ServiceCiReservas.todayReservationsRequestBody();
            return ((HotelWebServiceDB.ServiceCiReservas.WebService1Soap)(this)).todayReservationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelWebServiceDB.ServiceCiReservas.reservasPorCIResponse HotelWebServiceDB.ServiceCiReservas.WebService1Soap.reservasPorCI(HotelWebServiceDB.ServiceCiReservas.reservasPorCIRequest request) {
            return base.Channel.reservasPorCI(request);
        }
        
        public string reservasPorCI(string ci) {
            HotelWebServiceDB.ServiceCiReservas.reservasPorCIRequest inValue = new HotelWebServiceDB.ServiceCiReservas.reservasPorCIRequest();
            inValue.Body = new HotelWebServiceDB.ServiceCiReservas.reservasPorCIRequestBody();
            inValue.Body.ci = ci;
            HotelWebServiceDB.ServiceCiReservas.reservasPorCIResponse retVal = ((HotelWebServiceDB.ServiceCiReservas.WebService1Soap)(this)).reservasPorCI(inValue);
            return retVal.Body.reservasPorCIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceCiReservas.reservasPorCIResponse> HotelWebServiceDB.ServiceCiReservas.WebService1Soap.reservasPorCIAsync(HotelWebServiceDB.ServiceCiReservas.reservasPorCIRequest request) {
            return base.Channel.reservasPorCIAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelWebServiceDB.ServiceCiReservas.reservasPorCIResponse> reservasPorCIAsync(string ci) {
            HotelWebServiceDB.ServiceCiReservas.reservasPorCIRequest inValue = new HotelWebServiceDB.ServiceCiReservas.reservasPorCIRequest();
            inValue.Body = new HotelWebServiceDB.ServiceCiReservas.reservasPorCIRequestBody();
            inValue.Body.ci = ci;
            return ((HotelWebServiceDB.ServiceCiReservas.WebService1Soap)(this)).reservasPorCIAsync(inValue);
        }
    }
}
