//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebServiceDB.ServiceTodayReservations {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTodayReservations.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento allReservationsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/allReservations", ReplyAction="*")]
        HotelWebServiceDB.ServiceTodayReservations.allReservationsResponse allReservations(HotelWebServiceDB.ServiceTodayReservations.allReservationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/allReservations", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceTodayReservations.allReservationsResponse> allReservationsAsync(HotelWebServiceDB.ServiceTodayReservations.allReservationsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento simplesReservationsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/simplesReservations", ReplyAction="*")]
        HotelWebServiceDB.ServiceTodayReservations.simplesReservationsResponse simplesReservations(HotelWebServiceDB.ServiceTodayReservations.simplesReservationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/simplesReservations", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceTodayReservations.simplesReservationsResponse> simplesReservationsAsync(HotelWebServiceDB.ServiceTodayReservations.simplesReservationsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento todayReservationsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/todayReservations", ReplyAction="*")]
        HotelWebServiceDB.ServiceTodayReservations.todayReservationsResponse todayReservations(HotelWebServiceDB.ServiceTodayReservations.todayReservationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/todayReservations", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceTodayReservations.todayReservationsResponse> todayReservationsAsync(HotelWebServiceDB.ServiceTodayReservations.todayReservationsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class allReservationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="allReservations", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceTodayReservations.allReservationsRequestBody Body;
        
        public allReservationsRequest() {
        }
        
        public allReservationsRequest(HotelWebServiceDB.ServiceTodayReservations.allReservationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class allReservationsRequestBody {
        
        public allReservationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class allReservationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="allReservationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceTodayReservations.allReservationsResponseBody Body;
        
        public allReservationsResponse() {
        }
        
        public allReservationsResponse(HotelWebServiceDB.ServiceTodayReservations.allReservationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class allReservationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string allReservationsResult;
        
        public allReservationsResponseBody() {
        }
        
        public allReservationsResponseBody(string allReservationsResult) {
            this.allReservationsResult = allReservationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class simplesReservationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="simplesReservations", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceTodayReservations.simplesReservationsRequestBody Body;
        
        public simplesReservationsRequest() {
        }
        
        public simplesReservationsRequest(HotelWebServiceDB.ServiceTodayReservations.simplesReservationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class simplesReservationsRequestBody {
        
        public simplesReservationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class simplesReservationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="simplesReservationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceTodayReservations.simplesReservationsResponseBody Body;
        
        public simplesReservationsResponse() {
        }
        
        public simplesReservationsResponse(HotelWebServiceDB.ServiceTodayReservations.simplesReservationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class simplesReservationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string simplesReservationsResult;
        
        public simplesReservationsResponseBody() {
        }
        
        public simplesReservationsResponseBody(string simplesReservationsResult) {
            this.simplesReservationsResult = simplesReservationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class todayReservationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="todayReservations", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceTodayReservations.todayReservationsRequestBody Body;
        
        public todayReservationsRequest() {
        }
        
        public todayReservationsRequest(HotelWebServiceDB.ServiceTodayReservations.todayReservationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class todayReservationsRequestBody {
        
        public todayReservationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class todayReservationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="todayReservationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceTodayReservations.todayReservationsResponseBody Body;
        
        public todayReservationsResponse() {
        }
        
        public todayReservationsResponse(HotelWebServiceDB.ServiceTodayReservations.todayReservationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class todayReservationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string todayReservationsResult;
        
        public todayReservationsResponseBody() {
        }
        
        public todayReservationsResponseBody(string todayReservationsResult) {
            this.todayReservationsResult = todayReservationsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : HotelWebServiceDB.ServiceTodayReservations.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<HotelWebServiceDB.ServiceTodayReservations.WebService1Soap>, HotelWebServiceDB.ServiceTodayReservations.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelWebServiceDB.ServiceTodayReservations.allReservationsResponse HotelWebServiceDB.ServiceTodayReservations.WebService1Soap.allReservations(HotelWebServiceDB.ServiceTodayReservations.allReservationsRequest request) {
            return base.Channel.allReservations(request);
        }
        
        public string allReservations() {
            HotelWebServiceDB.ServiceTodayReservations.allReservationsRequest inValue = new HotelWebServiceDB.ServiceTodayReservations.allReservationsRequest();
            inValue.Body = new HotelWebServiceDB.ServiceTodayReservations.allReservationsRequestBody();
            HotelWebServiceDB.ServiceTodayReservations.allReservationsResponse retVal = ((HotelWebServiceDB.ServiceTodayReservations.WebService1Soap)(this)).allReservations(inValue);
            return retVal.Body.allReservationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceTodayReservations.allReservationsResponse> HotelWebServiceDB.ServiceTodayReservations.WebService1Soap.allReservationsAsync(HotelWebServiceDB.ServiceTodayReservations.allReservationsRequest request) {
            return base.Channel.allReservationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelWebServiceDB.ServiceTodayReservations.allReservationsResponse> allReservationsAsync() {
            HotelWebServiceDB.ServiceTodayReservations.allReservationsRequest inValue = new HotelWebServiceDB.ServiceTodayReservations.allReservationsRequest();
            inValue.Body = new HotelWebServiceDB.ServiceTodayReservations.allReservationsRequestBody();
            return ((HotelWebServiceDB.ServiceTodayReservations.WebService1Soap)(this)).allReservationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelWebServiceDB.ServiceTodayReservations.simplesReservationsResponse HotelWebServiceDB.ServiceTodayReservations.WebService1Soap.simplesReservations(HotelWebServiceDB.ServiceTodayReservations.simplesReservationsRequest request) {
            return base.Channel.simplesReservations(request);
        }
        
        public string simplesReservations() {
            HotelWebServiceDB.ServiceTodayReservations.simplesReservationsRequest inValue = new HotelWebServiceDB.ServiceTodayReservations.simplesReservationsRequest();
            inValue.Body = new HotelWebServiceDB.ServiceTodayReservations.simplesReservationsRequestBody();
            HotelWebServiceDB.ServiceTodayReservations.simplesReservationsResponse retVal = ((HotelWebServiceDB.ServiceTodayReservations.WebService1Soap)(this)).simplesReservations(inValue);
            return retVal.Body.simplesReservationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceTodayReservations.simplesReservationsResponse> HotelWebServiceDB.ServiceTodayReservations.WebService1Soap.simplesReservationsAsync(HotelWebServiceDB.ServiceTodayReservations.simplesReservationsRequest request) {
            return base.Channel.simplesReservationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelWebServiceDB.ServiceTodayReservations.simplesReservationsResponse> simplesReservationsAsync() {
            HotelWebServiceDB.ServiceTodayReservations.simplesReservationsRequest inValue = new HotelWebServiceDB.ServiceTodayReservations.simplesReservationsRequest();
            inValue.Body = new HotelWebServiceDB.ServiceTodayReservations.simplesReservationsRequestBody();
            return ((HotelWebServiceDB.ServiceTodayReservations.WebService1Soap)(this)).simplesReservationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelWebServiceDB.ServiceTodayReservations.todayReservationsResponse HotelWebServiceDB.ServiceTodayReservations.WebService1Soap.todayReservations(HotelWebServiceDB.ServiceTodayReservations.todayReservationsRequest request) {
            return base.Channel.todayReservations(request);
        }
        
        public string todayReservations() {
            HotelWebServiceDB.ServiceTodayReservations.todayReservationsRequest inValue = new HotelWebServiceDB.ServiceTodayReservations.todayReservationsRequest();
            inValue.Body = new HotelWebServiceDB.ServiceTodayReservations.todayReservationsRequestBody();
            HotelWebServiceDB.ServiceTodayReservations.todayReservationsResponse retVal = ((HotelWebServiceDB.ServiceTodayReservations.WebService1Soap)(this)).todayReservations(inValue);
            return retVal.Body.todayReservationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceTodayReservations.todayReservationsResponse> HotelWebServiceDB.ServiceTodayReservations.WebService1Soap.todayReservationsAsync(HotelWebServiceDB.ServiceTodayReservations.todayReservationsRequest request) {
            return base.Channel.todayReservationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelWebServiceDB.ServiceTodayReservations.todayReservationsResponse> todayReservationsAsync() {
            HotelWebServiceDB.ServiceTodayReservations.todayReservationsRequest inValue = new HotelWebServiceDB.ServiceTodayReservations.todayReservationsRequest();
            inValue.Body = new HotelWebServiceDB.ServiceTodayReservations.todayReservationsRequestBody();
            return ((HotelWebServiceDB.ServiceTodayReservations.WebService1Soap)(this)).todayReservationsAsync(inValue);
        }
    }
}
