//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebServiceDB.ServiceAllReservations {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAllReservations.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        HotelWebServiceDB.ServiceAllReservations.HelloWorldResponse HelloWorld(HotelWebServiceDB.ServiceAllReservations.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceAllReservations.HelloWorldResponse> HelloWorldAsync(HotelWebServiceDB.ServiceAllReservations.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento allReservationsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/allReservations", ReplyAction="*")]
        HotelWebServiceDB.ServiceAllReservations.allReservationsResponse allReservations(HotelWebServiceDB.ServiceAllReservations.allReservationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/allReservations", ReplyAction="*")]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceAllReservations.allReservationsResponse> allReservationsAsync(HotelWebServiceDB.ServiceAllReservations.allReservationsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceAllReservations.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(HotelWebServiceDB.ServiceAllReservations.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceAllReservations.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(HotelWebServiceDB.ServiceAllReservations.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class allReservationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="allReservations", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceAllReservations.allReservationsRequestBody Body;
        
        public allReservationsRequest() {
        }
        
        public allReservationsRequest(HotelWebServiceDB.ServiceAllReservations.allReservationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class allReservationsRequestBody {
        
        public allReservationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class allReservationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="allReservationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public HotelWebServiceDB.ServiceAllReservations.allReservationsResponseBody Body;
        
        public allReservationsResponse() {
        }
        
        public allReservationsResponse(HotelWebServiceDB.ServiceAllReservations.allReservationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class allReservationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string allReservationsResult;
        
        public allReservationsResponseBody() {
        }
        
        public allReservationsResponseBody(string allReservationsResult) {
            this.allReservationsResult = allReservationsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : HotelWebServiceDB.ServiceAllReservations.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<HotelWebServiceDB.ServiceAllReservations.WebService1Soap>, HotelWebServiceDB.ServiceAllReservations.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelWebServiceDB.ServiceAllReservations.HelloWorldResponse HotelWebServiceDB.ServiceAllReservations.WebService1Soap.HelloWorld(HotelWebServiceDB.ServiceAllReservations.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            HotelWebServiceDB.ServiceAllReservations.HelloWorldRequest inValue = new HotelWebServiceDB.ServiceAllReservations.HelloWorldRequest();
            inValue.Body = new HotelWebServiceDB.ServiceAllReservations.HelloWorldRequestBody();
            HotelWebServiceDB.ServiceAllReservations.HelloWorldResponse retVal = ((HotelWebServiceDB.ServiceAllReservations.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceAllReservations.HelloWorldResponse> HotelWebServiceDB.ServiceAllReservations.WebService1Soap.HelloWorldAsync(HotelWebServiceDB.ServiceAllReservations.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelWebServiceDB.ServiceAllReservations.HelloWorldResponse> HelloWorldAsync() {
            HotelWebServiceDB.ServiceAllReservations.HelloWorldRequest inValue = new HotelWebServiceDB.ServiceAllReservations.HelloWorldRequest();
            inValue.Body = new HotelWebServiceDB.ServiceAllReservations.HelloWorldRequestBody();
            return ((HotelWebServiceDB.ServiceAllReservations.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HotelWebServiceDB.ServiceAllReservations.allReservationsResponse HotelWebServiceDB.ServiceAllReservations.WebService1Soap.allReservations(HotelWebServiceDB.ServiceAllReservations.allReservationsRequest request) {
            return base.Channel.allReservations(request);
        }
        
        public string allReservations() {
            HotelWebServiceDB.ServiceAllReservations.allReservationsRequest inValue = new HotelWebServiceDB.ServiceAllReservations.allReservationsRequest();
            inValue.Body = new HotelWebServiceDB.ServiceAllReservations.allReservationsRequestBody();
            HotelWebServiceDB.ServiceAllReservations.allReservationsResponse retVal = ((HotelWebServiceDB.ServiceAllReservations.WebService1Soap)(this)).allReservations(inValue);
            return retVal.Body.allReservationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HotelWebServiceDB.ServiceAllReservations.allReservationsResponse> HotelWebServiceDB.ServiceAllReservations.WebService1Soap.allReservationsAsync(HotelWebServiceDB.ServiceAllReservations.allReservationsRequest request) {
            return base.Channel.allReservationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HotelWebServiceDB.ServiceAllReservations.allReservationsResponse> allReservationsAsync() {
            HotelWebServiceDB.ServiceAllReservations.allReservationsRequest inValue = new HotelWebServiceDB.ServiceAllReservations.allReservationsRequest();
            inValue.Body = new HotelWebServiceDB.ServiceAllReservations.allReservationsRequestBody();
            return ((HotelWebServiceDB.ServiceAllReservations.WebService1Soap)(this)).allReservationsAsync(inValue);
        }
    }
}
